name: Deploy Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Only allow one run at a time for this workflow
# See https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
# This workflow will only run once per this workflow name, and per ref (which is the branch or tag)
concurrency: ${{ github.workflow }}-${{ github.ref }}

# Required because we are using OIDC to connect to AWS
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # This will automatically checkout the correct branch
      - uses: actions/checkout@v3

      # Call the custom action this workflow shares with the PR workflow
      - uses: ./.github/actions/deploy
        with:
          # You would likely change the name of this secret
          aws-role-to-assume: ${{ secrets.OPENSOURCE_ACTIONS_ROLE_ARN }}
